name: SLSA Go releaser

on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  contents: write
  id-token: write
  actions: read

jobs:
  build:
    permissions:
      contents: write
      id-token: write
      actions: read
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v2.0.0
    with:
      go-version: "1.25"
      config-file: ./.github/slsa-goreleaser.yml
      workdir: ./cli
